In [1]:
import pandas as pd 
from tqdm import tqdm
from langdetect import detect, DetectorFactory
import tweepy
import csv

tqdm.pandas()

In [2]:
stock_bot = pd.read_csv("stockerbot-export.csv",error_bad_lines=False)

stocks_clean = pd.read_csv("stocks_cleaned.csv",error_bad_lines=False)

b'Skipping line 731: expected 8 fields, saw 13\nSkipping line 2836: expected 8 fields, saw 15\nSkipping line 3058: expected 8 fields, saw 12\nSkipping line 3113: expected 8 fields, saw 12\nSkipping line 3194: expected 8 fields, saw 17\nSkipping line 3205: expected 8 fields, saw 17\nSkipping line 3255: expected 8 fields, saw 17\nSkipping line 3520: expected 8 fields, saw 17\nSkipping line 4078: expected 8 fields, saw 17\nSkipping line 4087: expected 8 fields, saw 17\nSkipping line 4088: expected 8 fields, saw 17\nSkipping line 4499: expected 8 fields, saw 12\n'

In [3]:
stock_bot = stock_bot[stock_bot['text'].notnull()]
stock_bot

,id,text,timestamp,source,symbols,company_names,url,verified
0,1019696670777503700,VIDEO: “I was in my office. I was minding my o...,Wed Jul 18 21:33:26 +0000 2018,GoldmanSachs,GS,The Goldman Sachs,https://twitter.com/i/web/status/1019696670777...,True
1,1019709091038548000,The price of lumber $LB_F is down 22% since hi...,Wed Jul 18 22:22:47 +0000 2018,StockTwits,M,Macy's,https://twitter.com/i/web/status/1019709091038...,True
2,1019711413798035500,Who says the American Dream is dead? https://t...,Wed Jul 18 22:32:01 +0000 2018,TheStreet,AIG,American,https://buff.ly/2L3kmc4,True
3,1019716662587740200,Barry Silbert is extremely optimistic on bitco...,Wed Jul 18 22:52:52 +0000 2018,MarketWatch,BTC,Bitcoin,https://twitter.com/i/web/status/1019716662587...,True
4,1019718460287389700,How satellites avoid attacks and space junk wh...,Wed Jul 18 23:00:01 +0000 2018,Forbes,ORCL,Oracle,http://on.forbes.com/6013DqDDU,True
...,...,...,...,...,...,...,...,...
28259,1019730088617635800,$FB : 29234a9c-7f08-4d5a-985f-cb1a5554ecf9,Wed Jul 18 23:46:13 +0000 2018,test5f1798,FB,Facebook,NaN,False
28260,1019730115524288500,【仮想通貨】ビットコインの価格上昇、８０万円台回復 約１カ月半ぶり $BTC ht...,Wed Jul 18 23:46:19 +0000 2018,keizai_toushi17,BTC,Bitcoin,http://keizai-toushi-navi.com/?p=26838,False
28261,1019730115805184000,RT @invest_in_hd: 'Nuff said! $TEL #telcoin #...,Wed Jul 18 23:46:19 +0000 2018,iad81,BTC,Bitcoin,https://twitter.com/CRYPTOVERLOAD/status/10178...,False
28262,1019730117252341800,【仮想通貨】ビットコインの価格上昇、８０万円台回復 約１カ月半ぶり $BTC ht...,Wed Jul 18 23:46:20 +0000 2018,O8viWMyrCV6cBOZ,BTC,Bitcoin,http://true.velvet.jp/monexx/archives/2357,False
28263,1019730146180419600,Stellar $XLM price: $0.297852 Binance registra...,Wed Jul 18 23:46:27 +0000 2018,Descendent92,AMP,Ameriprise Financial,https://twitter.com/i/web/status/1019730146180...,False

In [4]:
stocks_clean

    ticker                  name
0     NVAX               Novavax
1     SIRI             Sirius XM
2      QQQ           Invesco QQQ
3     AAPL                 Apple
4     MSFT             Microsoft
..     ...                   ...
578    XYL                 Xylem
579    YUM           YUM! Brands
580    ZBH         Zimmer Biomet
581   ZION  Zions Bancorporation
582    ZTS                Zoetis

[583 rows x 2 columns]

In [5]:
def lang(text):
    try:
        DetectorFactory.seed = 0
        return detect(text)
    except:
        return None

In [6]:
stock_bot['language'] = stock_bot['text'].progress_apply(lambda x: lang(x))

100%|██████████| 28264/28264 [01:49<00:00, 257.13it/s]

In [7]:
stock_bot.to_csv('stock_bot_with_lang', index=False)

In [8]:
stock_bot.groupby('language').count().sort_values('id',ascending=False)

,id,text,timestamp,source,symbols,company_names,url,verified
language,,,,,,,,
en,26288,26288,26288,26288,26288,26287,20712,26288
de,509,509,509,509,509,509,393,509
es,227,227,227,227,227,227,88,227
ca,202,202,202,202,202,202,168,202
ja,163,163,163,163,163,163,69,163
id,79,79,79,79,79,79,35,79
sv,72,72,72,72,72,72,48,72
tl,67,67,67,67,67,67,32,67
pt,66,66,66,66,66,66,33,66
fr,61,61,61,61,61,61,40,61
ro,55,55,55,55,55,55,28,55
vi,48,48,48,48,48,48,28,48
cy,47,47,47,47,47,47,11,47
nl,40,40,40,40,40,40,27,40
da,39,39,39,39,39,39,24,39
no,38,38,38,38,38,38,19,38
so,36,36,36,36,36,36,18,36
it,35,35,35,35,35,35,25,35
af,32,32,32,32,32,32,10,32
et,28,28,28,28,28,28,23,28
hu,25,25,25,25,25,25,19,25
pl,19,19,19,19,19,19,10,19
sw,16,16,16,16,16,16,9,16
tr,12,12,12,12,12,12,5,12
ar,11,11,11,11,11,11,1,11
hr,9,9,9,9,9,9,7,9
sl,8,8,8,8,8,8,1,8
cs,5,5,5,5,5,5,2,5
ko,5,5,5,5,5,5,1,5
ru,4,4,4,4,4,4,0,4
fi,4,4,4,4,4,4,1,4
lv,3,3,3,3,3,3,0,3
sk,3,3,3,3,3,3,2,3
sq,3,3,3,3,3,3,1,3
lt,2,2,2,2,2,2,2,2
zh-cn,2,2,2,2,2,2,2,2

In [9]:
en_stock_bot = stock_bot[stock_bot['language'] == 'en']

In [10]:
CustomerKey = ""
CustomerSecretKey = ""
AccessToken = ""
AccessTokenSecret = ""

In [51]:
# Creating the authentication object
auth = tweepy.OAuthHandler(CustomerKey, CustomerSecretKey)

# Setting your access token and secret
auth.set_access_token(AccessToken, AccessTokenSecret)

# Creating the API object while passing in auth information
api = tweepy.API(auth,wait_on_rate_limit=True)
# #
# row_list = [["created_at", "Tweet_id","full_text", "entities","geo","source","user_id_str","user_name","user_location","user_description","user_followers_count","user_friends_count",
#              "user_created_at","user_verified","user_statuses_count","favorited","favorite_count","retweet_count","reply_count","profile_image_url_https","keyword_contained"]]

row_list = []

# The search term you want to find
# Language code (follows ISO 639-1 standards)
language = "en"

queries = ["BTC"]

# queries = ["ชาติบ้านเมือง","แผ่นดิน","#อนุชนรักชาติศาสน์กษัตริย์"]
# Calling the user_timeline function with our parameters
# results = api.search(q=query, lang=language,tweet_mode='extended')

for query in queries:
    max_tweets = 2000
    searched_tweets = [status for status in tweepy.Cursor(api.search, q=query,lang=language,tweet_mode='extended').items(max_tweets)]
    
   # foreach through all tweets pulled
    for tweet in tqdm(searched_tweets):
       # printing the full_text stored inside the tweet object
       if (not tweet.retweeted) and ('RT @' not in tweet.full_text):
           if ("reply_count" not in tweet._json):
               tweetlist = [tweet.created_at, tweet.id_str, tweet.full_text, tweet.entities,tweet.geo,tweet.source,
                            tweet.user.id_str, tweet.user.name, tweet.user.location,tweet.user.description,
                            tweet.user.followers_count, tweet.user.friends_count,
                            tweet.user.created_at, tweet.user.verified,
                            tweet.user.statuses_count, tweet.favorited,
                            tweet.favorite_count, tweet.retweet_count, 0,
                            tweet.user.profile_image_url_https, query]
           else:
               tweetlist = [tweet.created_at,tweet.id_str, tweet.full_text, tweet.entities,tweet.geo,tweet.source,
                            tweet.user.id_str, tweet.user.name, tweet.user.location,tweet.user.description,
                            tweet.user.followers_count, tweet.user.friends_count,
                            tweet.user.created_at, tweet.user.verified,
                            tweet.user.statuses_count, tweet.favorited,
                            tweet.favorite_count, tweet.retweet_count, tweet.reply_count,
                            tweet.user.profile_image_url_https, query]
           if tweetlist not in row_list:
               row_list.append(tweetlist)

with open('TwitterDB_BTC.csv', 'a', newline='') as file:
   writer = csv.writer(file)
   writer.writerows(row_list)

100%|██████████| 2000/2000 [00:00<00:00, 207397.53it/s]

In [2]:
btc = pd.read_csv('TwitterDB_BTC.csv')

In [3]:
btc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1104 entries, 0 to 1103
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   created_at               1104 non-null   object
 1   Tweet_id                 1104 non-null   object
 2   full_text                1104 non-null   object
 3   entities                 1104 non-null   object
 4   geo                      3 non-null      object
 5   source                   1104 non-null   object
 6   user_id_str              1104 non-null   object
 7   user_name                1104 non-null   object
 8   user_location            503 non-null    object
 9   user_description         965 non-null    object
 10  user_followers_count     1104 non-null   object
 11  user_friends_count       1104 non-null   object
 12  user_created_at          1104 non-null   object
 13  user_verified            1104 non-null   object
 14  user_statuses_count      1104 non-null   object
 15  favorited                1104 non-null   object
 16  favorite_count           1104 non-null   object
 17  retweet_count            1104 non-null   object
 18  reply_count              1104 non-null   object
 19  profile_image_url_https  1104 non-null   object
 20  keyword_contained        1104 non-null   object
dtypes: object(21)
memory usage: 181.2+ KB

In [4]:
btc = btc[btc['user_followers_count'].apply(lambda x: x.isnumeric())]
btc['user_followers_count'] = btc['user_followers_count'].astype('float64')
btc['user_followers_level'] = pd.qcut(btc['user_followers_count'], 5, labels=["low", "slightly medium", "medium","slightly high", "high"])

In [5]:
high_btc = btc[btc['user_followers_level']=='high']
high_btc = high_btc[['Tweet_id','created_at','full_text','user_id_str','user_name',
          'user_followers_count','user_followers_level']]

In [13]:
high_btc.to_csv('HighFollowBTC.csv',index=False)

In [12]:
high_btc.sort_values('user_followers_count')

,Tweet_id,created_at,full_text,user_id_str,user_name,user_followers_count,user_followers_level
159,1438496107605205000,2021-09-16 13:32:52,Roundup/Thoughts on 6-7 coins coming to my Pat...,93608509,Crypto Mobster,29595.0,high
155,1438496144024240130,2021-09-16 13:33:01,BTC/USD | $BTCUSD | $BTC $USD\n\n18 0000 BTC\n...,1067310570695577600,Crypto Blitz,6737.0,high
153,1438496154774294529,2021-09-16 13:33:03,$BTC\n\nGot that reversal candle confirmed on ...,1091099554605395968,Don't follow Shardi B if you hate money,172208.0,high
150,1438496158179942404,2021-09-16 13:33:04,#Bitcoin #BTCpriceprediction New Bitcoin price...,330555324,dumbwire CryptoNews 📟,29099.0,high
151,1438496156669992963,2021-09-16 13:33:04,If you like my work support my sponsor and get...,1091099554605395968,Don't follow Shardi B if you hate money,172208.0,high
...,...,...,...,...,...,...,...
385,1441072405426974720,2021-09-23 16:10:09,Chiefra don’t miss ✅ \n\n$BTC short alerted in...,1417594995503210499,chiefraT,2582.0,high
384,1441072410451533832,2021-09-23 16:10:11,Crypto Trading Now Official in Dubai Following...,771502019471220736,CryptoNewswire 🌐,9428.0,high
380,1441072450918227977,2021-09-23 16:10:20,"Crypto market sentiment has briefly picked up,...",1397073609739235331,Crypto Line 📈,9374.0,high
366,1441072565431128067,2021-09-23 16:10:48,@ronnie_184 @HeroFiio @Cronald81 @CoinLAB_Offi...,1017272628900388864,FinnBTC,7531.0,high
348,1441072669768753155,2021-09-23 16:11:12,@MotleyInvestor Here's where I struggle: for E...,14280977,clay.c/,27524.0,high

In [10]:
btc.sort_values('created_at')

,created_at,Tweet_id,full_text,entities,geo,source,user_id_str,user_name,user_location,user_description,...,user_created_at,user_verified,user_statuses_count,favorited,favorite_count,retweet_count,reply_count,profile_image_url_https,keyword_contained,user_followers_level
161,2021-09-16 13:32:47,1438496083903238149,@bitpanda Blue BTC Weed cookies 🤪,"{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,Twitter Web App,20717117,JoseM,NaN,🇵🇹,...,2009-02-12 20:55:54,False,4575,False,0,0,0,https://pbs.twimg.com/profile_images/114141043...,BTC,medium
160,2021-09-16 13:32:52,1438496105205956610,Just look at that volume on 4hr chart on $STRA...,"{'hashtags': [{'text': 'bitcoin', 'indices': [...",NaN,Twitter for Android,1368629670875258880,Jack moris,NaN,Things our traders know: be careful of the hyp...,...,2021-03-07 18:28:55,False,13527,False,0,0,0,https://pbs.twimg.com/profile_images/140669271...,BTC,slightly high
159,2021-09-16 13:32:52,1438496107605205000,Roundup/Thoughts on 6-7 coins coming to my Pat...,"{'hashtags': [], 'symbols': [{'text': 'FOMO', ...",NaN,Twitter Web App,93608509,Crypto Mobster,United Kingdom,#Bitcoin | Boss of @LearnCryptoUK & @HitmanTra...,...,2009-11-30 11:05:24,False,56297,False,2,0,0,https://pbs.twimg.com/profile_images/136594214...,BTC,high
158,2021-09-16 13:32:54,1438496115993845762,@jamesjgriffin @DickWhitman_BTC Anything with ...,"{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,Twitter for iPhone,1379419853929467905,HODLmatt 🟩 🇸🇻⚡️🌋,NaN,"#bitcoin only, HODLER of last resort, Layered ...",...,2021-04-06 13:05:08,False,1963,False,0,0,0,https://pbs.twimg.com/profile_images/137942011...,BTC,medium
157,2021-09-16 13:32:55,1438496117478543360,@CoinCornerMolly Monday morning about 3am CST....,"{'hashtags': [{'text': 'btc', 'indices': [92, ...",NaN,Twitter for Android,34134410,Makelegs,NaN,#Bitcoin,...,2009-04-22 01:46:12,False,19317,False,0,0,0,https://pbs.twimg.com/profile_images/823366969...,BTC,slightly high
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,2021-09-23 16:11:10,1441072658385231878,Who wants gold when you can have Future ? #BTC...,"{'hashtags': [{'text': 'BTC', 'indices': [42, ...",NaN,Twitter for iPhone,3400827322,vΞΛC,NaN,✕ ¤ ✕ ¤ ✕ ¤ ✕ ¤ ✕ ¤ ✕ ¤ ✕ ¤ ✕ ¤ ✕ ¤ ✕ ¤ ✕ ¤ ✕ ...,...,2015-08-03 01:13:49,False,254,False,0,0,0,https://pbs.twimg.com/profile_images/144038683...,BTC,low
349,2021-09-23 16:11:12,1441072668493717511,$LUFFY is on Hotbit!\n\nDont zzZzzzZ\n\nSo che...,"{'hashtags': [{'text': 'saitama', 'indices': [...",NaN,Twitter for Android,1295436963483459586,Glitch3d P4ch0,The Abyss,Music Producer & NFT Creator\n#HICETNUNC2000,...,2020-08-17 19:07:01,False,177,False,0,0,0,https://pbs.twimg.com/profile_images/143381738...,BTC,slightly medium
348,2021-09-23 16:11:12,1441072669768753155,@MotleyInvestor Here's where I struggle: for E...,"{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,Twitter Web App,14280977,clay.c/,NaN,CEO @NomicsFinance. 90% of new cryptoassets ar...,...,2008-04-02 06:01:15,True,10516,False,0,0,0,https://pbs.twimg.com/profile_images/143637015...,BTC,high
347,2021-09-23 16:11:13,1441072670452375554,⚠️ Top past 24h performers in *MIDCAP* (coins ...,"{'hashtags': [{'text': 'crypto', 'indices': [1...",NaN,ufo2021test,1384497485167697921,👽🛸🧐 Crypto News--FOLLOW ME🛸👽🧐,"Roswell, New Mexico",I am bot telling u what items to spend your cr...,...,2021-04-20 13:21:51,False,1752,False,0,0,0,https://pbs.twimg.com/profile_images/138615533...,BTC,slightly medium
346,2021-09-23 16:11:14,1441072677213642753,@steve_hanke The professor is determined by ex...,"{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,Twitter for Android,1097530994851233792,Bahittin IŞIK,NaN,NaN,...,2019-02-18 16:19:15,False,2096,False,0,0,0,https://pbs.twimg.com/profile_images/139437222...,BTC,slightly medium

In [8]:
btc.groupby('user_followers_count').count().sort_values('Tweet_id',ascending=False)

,created_at,Tweet_id,full_text,entities,geo,source,user_id_str,user_name,user_location,user_description,...,user_created_at,user_verified,user_statuses_count,favorited,favorite_count,retweet_count,reply_count,profile_image_url_https,keyword_contained,user_followers_level
user_followers_count,,,,,,,,,,,,,,,,,,,,,
1.0,39,39,39,39,0,39,39,39,1,24,...,39,39,39,39,39,39,39,39,39,39
11.0,30,30,30,30,0,30,30,30,3,27,...,30,30,30,30,30,30,30,30,30,30
5.0,27,27,27,27,0,27,27,27,0,21,...,27,27,27,27,27,27,27,27,27,27
12.0,24,24,24,24,0,24,24,24,2,5,...,24,24,24,24,24,24,24,24,24,24
27.0,22,22,22,22,0,22,22,22,0,21,...,22,22,22,22,22,22,22,22,22,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
578.0,1,1,1,1,0,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
569.0,1,1,1,1,0,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
565.0,1,1,1,1,0,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
564.0,1,1,1,1,0,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
1225515.0,1,1,1,1,0,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [ ]:
row_list